namespace: rridane
name: kubernetes_admin
version: 0.8.0

readme: README.md

authors:
  - rridane <rridane@rr-dev.com>

description: >
  k8s adminstration toolkit

license:
  - MIT

tags:
  - ansible
  - linux
  - kubernetes
  - debian
  - ubuntu

dependencies: {}

repository: https://github.com/rridane/ansible-kubernetes-admin
documentation: https://github.com/rridane/ansible-kubernetes-admin
homepage: https://github.com/rridane/ansible-kubernetes-admin
issues: https://github.com/rridane/ansible-kubernetes-admin

build_ignore:
  # VCS / IDE / env
  - ".git"
  - ".git/**"
  - ".github"
  - ".github/**"
  - ".gitignore"
  - ".editorconfig"
  - ".pre-commit-config.yaml"
  - ".idea"
  - ".idea/**"
  - ".vscode"
  - ".vscode/**"

  # Environnements virtuels (tous niveaux)
  - ".venv"
  - ".venv/**"
  - "venv"
  - "venv/**"
  - "**/.venv"
  - "**/.venv/**"
  - "**/venv"
  - "**/venv/**"

  # Caches/tests
  - ".tox"
  - ".tox/**"
  - ".mypy_cache"
  - ".mypy_cache/**"
  - "__pycache__"
  - "**/__pycache__/**"
  - ".pytest_cache"
  - ".pytest_cache/**"

  # Artefacts
  - "dist"
  - "dist/**"
  - "*.tar.gz"
  - "*.zip"
  - "*.log"
  - "*.retry"

  # Molecule (si tu ne veux pas les publier)
  - "roles/*/molecule"
  - "roles/*/molecule/**"

  # Docs lourdes
  - "docs"
  - "docs/**"
  - "assets"
  - "assets/**"
  - "images"
  - "images/**"
  - "screenshots"
  - "screenshots/**"

  - "roles/*/files/*.tar"
  - "roles/*/files/*.tar.gz"
  - "roles/*/files/*.tgz"
  - "roles/*/files/*.zip"
  - "roles/*/files/*.deb"
  - "roles/*/files/*.rpm"
