---
# vars file for k8s_upgrade_node
_k8s_upgrade_semver: "{{ k8s_upgrade_version | regex_replace('^v', '') }}"
_k8s_upgrade_target: "v{{ _k8s_upgrade_semver }}"
_k8s_upgrade_target_minor: "{{ _k8s_upgrade_semver.split('.')[1] | int }}"
_k8s_kubectl: "kubectl --kubeconfig {{ k8s_upgrade_kubeconfig }}"
_k8s_kubeadm: "{{ (['env'] + (k8s_upgrade_kubeadm_unset_env | map('regex_replace', '^', '-u ') | list) + ['kubeadm']) | join(' ') if (k8s_upgrade_kubeadm_unset_env | length > 0) else 'kubeadm' }}"
